### ISSUE TITLE
Problem mit PDF

### ISSUE THREAD

**Issue by HerroBert** [rumpeltux/onlineticket#15]
Es mag mein Ticket-PDF nicht:

# ./parsepdfs.sh Ticket-2-Print.pdf 
Ticket-2-Print.pdf : image extraction
Syntax Error: Can't get Fields array<0a>

pdfinfo:
Creator:         Adobe LiveCycle Designer 11.0
Producer:        Adobe XML Form Module Library
CreationDate:    Wed Dec 27 13:58:52 2023 CET
ModDate:         Wed Dec 27 13:58:52 2023 CET
Custom Metadata: no
Metadata Stream: yes
Tagged:          yes
UserProperties:  no
Suspects:        no
Form:            AcroForm
**Syntax Error: Can't get Fields array<0a>**
JavaScript:      no
Pages:           1
Encrypted:       no
Page size:       595.276 x 841.89 pts (A4)
Page rot:        0
File size:       114495 bytes
Optimized:       no
PDF version:     1.6

**Comment by rumpeltux** [comment]
Please provide repro instructions (e.g. can you attach the ticket?)

**Comment by HerroBert** [comment]
I guess, I cannot provide a non-personal ticket file...

**Comment by danielmarschall** [comment]
The question is, if the process fails due to the UIC 2.0 content (I guess this is expected, see #16 ) or if the PDF  file itself has a different structure nowadays so that the QR code cannot be extracted in the first place. How to find out?
