### ISSUE TITLE
Automatically detect if --zxing is required?

### ISSUE THREAD

**Issue by danielmarschall** [rumpeltux/onlineticket#18]
I have found out that some of my tickets only work if `--zxing` is added, and some of my tickets only work if `--zxing` is NOT added.

I would prefer if the script can run mostly automatical, so it could be executed in a batch file. I have changed the code a bit to address that:

```
  for ticket in args.ticket_files:
    try:
      tickets = [bytes.fromhex(line) for line in open(ticket)]
    except:
      content = open(ticket, 'rb').read()
      tickets = [content]
    for line_no, binary_ticket in enumerate(tickets):
      logging.info(f'File: {ticket}\tLine: {line_no + 1}')
      ot = None
      try:
        ot = OT(binary_ticket)
      except Exception as e:
        fixed = fix_zxing(binary_ticket)
        ot = OT(fixed)
      print(ot)
      ots.setdefault(ticket, []).append(ot)
```

This works so far. If `OT(binary_ticket)` fails, then `OT(fixed)` will be tested. This code resulted in 100% of my 62 collected being parsed correctly.

Unfortunately, this has a small cosmetic problem remaining:
If `ot = OT(binary_ticket)` fails, there will be a STDERR output. How can we avoid that?

```
WARNING:root:Couldn't decode (('data_length', 4, <class 'int'>), b'\xc3\xa2\xc3\x9e', <class '__main__.OT'>):

header: b'#UT'
version:        b'01'
carrier:        b'0080'
key_id: b'00007'
signature:      ("SubstrateUnderrunError('57<20 at <TagSet object, tags 192:0:3>')", b'0,\x02\x14\x1eI\x06Ll\xc2\x87\xc2\x91O\xc3\x85&\xc2\xb8\xc2\x80m\xc3\xa9\xc3\xb9\x08P\xc2\x87\xc3\x8b#\x02\x145\xc2\x86E\xc2\x9a\xc3\xa2}|\xc3\x9a\x0fV!')

```

**Comment by rumpeltux** [comment]
This was the behavior before. Added `--auto-zxing` that keeps the behavior you were relying on.
And `--quiet` will drop the warning message.
