### ISSUE TITLE
Cant read "Studenten Deutschlandticket NRW"

### ISSUE THREAD

**Issue by lewinpauli** [rumpeltux/onlineticket#20]
used latest version of repo

txt file from pdf:

[myTicketFull.pdf-006.pbm.txt](https://github.com/rumpeltux/onlineticket/files/14888837/myTicketFull.pdf-006.pbm.txt)

I am currently trying to get some data out of the "DeutschlandSemesterTicket" but no open source scanner I tried is capable of that.

the source of the ticket is www.ots-nrw.de

I try to get the time until the ticket is valid, the signature validation and the allowed region 

You would help me a lot

**Comment by rumpeltux** [comment]
Your ticket doesn’t seem to be using UIC standard, so is probably some other proprietary encoding.
If you figure out how to read them, let me know :)
