### ISSUE TITLE
Weitere Informationen und Quellen

### ISSUE THREAD

**Issue by sigalor** [rumpeltux/onlineticket#4]
Hallo!

Zuerst einmal vielen Dank für dieses großartige Repository und die gefundenen und zusammengetragenen  Informationen! Dennoch ist mir aufgefallen, dass viele Quellenangaben fehlen, die ich durch eigene Recherche gefunden habe und gern beitragen möchte. Fast alle Links führen zum Internet Archive, um von ggf. in der Zukunft zurückgezogenen Dokumenten unabhängig zu sein.

1. Das in [`onlineticket.py`](https://github.com/rumpeltux/onlineticket/blob/master/onlineticket.py#L34) verlinkte PDF [HandyTicket-Fahrausweise des VRR im VDV-Barcode – Ein Kompendium zur Dekodierung](https://web.archive.org/web/20101206213922/http://www.kcefm.de/imperia/md/content/kcefm/kcefmvrr/2010_02_12_kompendiumvrrfa2dvdv_1_4.pdf). Der Link im derzeitgen Code ist tot.
2. [Kontrolle des UIC 918.3*-Barcodes](https://web.archive.org/web/20180905231149/https://www.bahn.de/p/view/angebot/regio/barcode.shtml) mit weiteren interessanten Informationen und Links. Hier wird mehrfach auf die E-Mail-Adresse _dbbarcode@deutschebahn.com_ verwiesen; möglicherweise würde das Erhalten des öffentlichen Schlüssels dieses Projekt voranbringen. Weitere Beschäftigung mit der Signatur und die Auslotung möglicher Schwachstellen sollte ebenso erstrebenswert sein.
3. [dbuic2vdvbc](https://sourceforge.net/projects/dbuic2vdvbc/), eine Referenzimplementierung für die Dekodierung, geschrieben in C. Beim Bauen des Quellcodes kann das `configure`-Skript mit dem Parameter `--enable-build-doc=yes` aufgerufen werden (und dann `make`), um die Dokumentation zusätzlich zu der `libdbuic2vdvbc.a` zu erstellen. Außerdem sind viele Beispiele und auch Beispieldaten enthalten. Ich finde es fast schon beeindruckend, dass dieser Code unter der BSD-Lizenz steht.
4. [B@hnDirekt – Interoperabilität Barcode DB Online-Ticket VDV- KA](https://web.archive.org/web/20180905231217/https://www.bahn.de/p/view/mdb/bahnintern/angebotsberatung/regio/barcode/mdb_220334_interoperabilitaet_barcode_db_online-ticketvdv-ka_v1_4.pdf) mit weiteren, eventuell aktuelleren Informationen als in [1].
5. Die [VDV-Kernapplikation](https://oepnv.eticket-deutschland.de/produkte-und-services/vdv-kernapplikation/#slide2), deren relevante Downloads offenbar allerdings nur nach einer Registierung oder Bezahlung eines Endbetrages verfügbar sind.

**Comment by justusjonas74** [comment]
Hallo, 

bzgl. der Signatur ist auch [diese Website](https://railpublickey.uic.org) wichtig. Hier findet man einige öffentliche Schlüssel der UIC-Unternehmen. Unter anderem der DB. Mit diesem kann man die Signatur der Barcodes prüfen. Ich habe (aufbauend auf diesem Projekt) eine JavaScript-Version [(justusjonas74/uic-918-3)](https://github.com/justusjonas74/uic-918-3) erstellt, welche auch in der Lage ist, die Sigantur zu prüfen. Vielleicht kann das jemand nach Python portieren.

**Comment by dd23** [comment]
Ich hab mich mal an der Implementierung von @justusjonas74 orientiert und das grundlegend in den Python code hier integriert.
Siehe #5

**Comment by rumpeltux** [comment]
Vielen Dank! Hab die Informationen jetzt in die README integriert.

**Comment by danielmarschall** [comment]
Das Dokument "Interoperabilität Barcode DB Online-TicketVDV-KA" gibt es in Version 1.5 hier:
https://assets.static-bahn.de/dam/jcr:8fa0c0b5-d7b8-443b-b3cd-7ae902884847/236539-315207.pdf
