### ISSUE TITLE
Exception java.lang.NoClassDefFoundError: com/google/zxing/NotFoundException

### ISSUE THREAD

**Issue by konkonchum** [rumpeltux/onlineticket#7]
Hallo, ich bekomme beim durchführen von sh parsepdfs.sh folgende Fehlermeldung. Was kann ich tun?

> sh parsepdfs.sh        
>       
> Exception in thread "main" java.lang.NoClassDefFoundError: com/google/zxing/NotFoundException
> 	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:99)
> 
> Caused by: java.lang.ClassNotFoundException: com.google.zxing.NotFoundException
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 1 more

**Comment by quinn-dev** [comment]
DE: In Zeile 7 `http` zu `https` umwandeln. Unverschlüsselte Verbindungen werden von maven nicht mehr unterstützt.
EN: Convert `http` to `https` in line 7. Maven no longer supports insecure connections.

https://github.com/rumpeltux/onlineticket/blob/56149e2a3ba9a7503dac25963356b8ec427ca1d3/parsepdfs.sh#L7

Siehe PR #8 / see PR #8.
